# include guard -------------------------------------------------------------- #
include_guard(GLOBAL)

# Prologue ------------------------------------------------------------------- #
CF_module_prologue(Printer)
# ---------------------------------------------------------------------------- #

macro(CF_print_var __var)
    if(DEFINED ${__var})
        message(STATUS "${CF_lp_Printer} `${__var}` : ${${__var}}")
    else()
        message(WARNING "${CF_lp_Printer} `${__var}` not defined")
    endif()
endmacro()

macro(CF_print_env _env_var)
    if(DEFINED ENV{${_env_var}})
        message(STATUS "${CF_lp_Printer} `ENV:${_env_var}` : $ENV{${_env_var}}")
    else()
        message(WARNING "${CF_lp_Printer} `ENV:${_env_var}` not defined")
    endif()
endmacro()

macro(CF_print_list _list_var)
    if(DEFINED ${_list_var})
        set(i 0)
        foreach(item IN LISTS ${_list_var})
            message(STATUS "${CF_lp_Printer} `${_list_var}[${i}]` : ${item}")
            math(EXPR i "${i} + 1")
        endforeach()
        unset(i)
        unset(item)
    else()
        message(WARNING "${CF_lp_Printer} `${_list_var}` not defined")
    endif()
endmacro()

function(CF_print_table _list_var _columns)
    if(_columns LESS_EQUAL 0)
        message(WARNING "${CF_lp_Printer} Columns must non negative")
        return()
    endif()
    if(NOT DEFINED ${_list_var})
        message(WARNING "${CF_lp_Printer} `${_list_var}` not defined")
    endif()
    set(i 0)
    set(__line "${CF_lp_Printer}")

    foreach(__item IN LISTS ${_list_var})
    if(i EQUAL ${_columns})
        message(STATUS  "${__line}")
        set(__line "${CF_lp_Printer}")
        set(i 0)
    endif()

    math(EXPR i "${i} + 1")
    string(APPEND __line " ${__item}")
    endforeach()
    message(STATUS "${__line}")
endfunction()

macro(CF_print_map _map_var)
    if(DEFINED ${_map_var})
        foreach(item IN LISTS ${_map_var})
            CF_print_var(${item})
        endforeach()
        unset(item)
    else()
        message(WARNING "${CF_lp_Printer} `${_map_var}` not defined")
    endif()
endmacro()

# Epilogue ------------------------------------------------------------------- #
CF_module_epilogue()
# ---------------------------------------------------------------------------- #